dataset:
  data_dir: /content/HASOC-Dravidian/dataset/data
  file_name: tamil_offensive_
model:
  model_loc: /content/drive/MyDrive/HASOC/transformer
  model: xlm-roberta-base #distilbert-base-cased #google/muril-base-cased #monsoon-nlp/tamillion #ai4bharat/indic-bert
  ckpt:
hyperparameters:
  lr: 1e-5
  epochs: 30
  batch_size: 32
  use_weights: True
  hidden_layers: 768
  dropout: 0.5
  max_len: 256
