dataset:
  data_dir: ./dataset/data #/content/HASOC-Dravidian/dataset/data
  file_name: tamil_codemix_offensive_
model:
  model_loc: /content/drive/MyDrive/HASOC/transformer
  model: distilbert-base-multilingual-cased #bert-base-multilingual-uncased #xlm-roberta-base #google/muril-base-cased #ai4bharat/indic-bert
  ckpt:
hyperparameters:
  lr: 1e-5
  epochs: 30
  batch_size: 32
  use_weights: True
  hidden_layers: 768
  dropout: 0.5
  max_len: 256
inference:
  save_representations: True
  mode: train
  batch_size: 1
