dataset:
  data_dir: ./dataset/data
  file_name: tamil_offensive_
model:
  model_loc: /content/drive/MyDrive/HASOC/transformer
  model: bert-base-multilingual-cased #google/muril-base-cased #monsoon-nlp/tamillion
  ckpt: 
hyperparameters:
  lr: 2e-5
  epochs: 10
  batch_size: 8
  